pub mod account_book;
pub mod accounts;
pub mod cancel_all_options_orders;
pub mod cancel_options_order;
pub mod countdown_cancel_options_orders;
pub mod create_options_order;
pub mod get_mmp_settings;
pub mod get_options_order;
pub mod get_options_position;
pub mod get_options_positions;
pub mod list_options_orders;
pub mod mmp_settings;
pub mod order;
pub mod position;
pub mod position_close_history;
pub mod reset_mmp;
pub mod settlements;
pub mod trades;
pub mod update_mmp_settings;

pub use crate::gateio::{PrivateRestClient as RestClient, RestResult};
