pub mod accounts;
pub mod amend_batch_orders;
pub mod amend_order;
pub mod batch_orders;
pub mod cancel_all_orders;
pub mod cancel_order;
pub mod countdown_cancel_all;
pub mod create_order;
pub mod get_dual_mode_position;
pub mod get_futures_position;
pub mod get_futures_positions;
pub mod get_order;
pub mod list_orders;
pub mod list_orders_by_time_range;
pub mod order;
pub mod position;
pub mod set_dual_mode;
pub mod set_position_leverage;
pub mod switch_to_cross_margin;
pub mod update_dual_mode_position_leverage;
pub mod update_dual_mode_position_margin;
pub mod update_dual_mode_position_risk_limit;
pub mod update_position_margin;
pub mod update_position_risk_limit;

pub use crate::gateio::{PrivateRestClient as RestClient, RestResult};
