[package]
name = "binance_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
quote = "1.0.40"
syn = "2.0.101"

[lints]
workspace = true

[lib]
proc-macro = true
