[package]
name = "secrets"
version = "0.1.0"
edition = "2024"
description = "Secret handling utilities and traits for ccrxt"
license = "MIT"

[dependencies]
secrecy = "0.10.3"

[lints]
workspace = true
